require: rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'jekyll-pseudohiki.gemspec'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80

Naming/FileName:
  Enabled: false
